### ISSUE TITLE
wow.. this is awesome..

### ISSUE THREAD

**Issue by 1c7** [aatishb/entropy#7]
I mean this.
https://aatishb.github.io/entropy/

Can I translate it into chinese??

**Comment by aatishb** [comment]
Yes, please do! That would be amazing.

**Comment by 1c7** [comment]
@aatishb :D
If I got time and finish translate, I would @ you again let you know~

**Comment by bringyou** [comment]
@1c7 Do you mind my taking over this translating? I'll submit a pull request when done

**Comment by 1c7** [comment]
@bringyou sure.
这个我好像立了 flag 忘记了。哈哈。
那麻烦你来做吧

**Comment by aatishb** [comment]
Yes, please go for it! Thank you. :)
