### ISSUE TITLE
Wrong conclusion

### ISSUE THREAD

**Issue by catamphetamine** [aatishb/entropy#8]
The conclusion you make in the end is wrong

> The mystery is, at the level of atoms and molecules, each of these processes are reversible. But when we get to bigger collections of atoms, a kind of one-way street emerges — a macroscopic irreversibility arises from microscopically reversible parts. Things spontaneously happen in the direction of increasing entropy, never in the opposite direction.
> Now we know why. There’s no microscopic law telling any particle which direction to go, just like there’s no shepherd telling the sheep where to go in our imaginary farm. It’s just that there are more ways to spread energy around, and fewer ways to keep energy confined. Increasing entropy is highly likely, decreasing it is basically impossible. It’s just stuff obeying the laws of chance.

The real explanation is that the "moving balls" are the way "macroscopic" things work, but there are no "balls" analogy on the microscopic level. All those "ball" electrons circling around the positively charged atom core is basically bullshit. They say they have to explain kids how things work and therefore they lie. And then these kids age and are driven insane with the "explanations" like that: why are the balls perfectly reversible and yet the entropy thing.

The real reason is that THERE IS NO SUCH THING AS BALLS found inside the stuff. It's just MATH. MATH and nothing more. Our world is made of pure math, not of balls. And it's a very intimidating thing once you realise it. Then you start believing in God.

**Comment by catamphetamine** [comment]
Furthermore, the sheep analogy is probably wrong here, because you're basing your explanation on the fact that sheep are constantly teleporting from one place to another which is absurd: molecules of ice do not constantly teleport from one random place to another.

**Comment by aatishb** [comment]
Your comments demonstrate a few misunderstandings:
1. on models: No model is a 100% accurate reproduction of reality, but they are useful if they capture certain essential features, e.g. if they make predictions that match experiments. A billiard ball model of atoms is indeed useful, and can be used to correctly derive classical macroscopic relations, such as the ideal gas law. In a different context (such as a different length scale), a model can be less useful, and so you switch to another model.
2. On "balls": The piece didn't assume a classical billiard ball style model of particles. The sheep analogy was more subtle than that. It was used to explain a quantum mechanical model of energy packets being arranged in solids, a model whose mathematical predictions accurately capture many features of real world solids. See e.g. https://en.wikipedia.org/wiki/Einstein_solid or http://hyperphysics.phy-astr.gsu.edu/hbase/therm/einsol.html for more.
3. The statement that 'it's all just math' isn't particularly helpful. It doesn't add to someone's understanding in any way. In fact it can do the opposite, by mystifying needlessly. The sheep analogy and the blog post you read was my attempt to actually _explain_ the math involved, without using equations. After all, math isn't mystical, it's a process that can be explained.

**Comment by catamphetamine** [comment]
whatever
